<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.538">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Abdur Rafi">
<meta name="dcterms.date" content="2024-01-10">

<title>ANALISIS PENGARUH KUANTITAS TERHADAP NILAI EKSPOR KOPI INDONESIA DALAM 10 TAHUN TERAKHIR (2013-2022)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ANALISIS PENGARUH KUANTITAS TERHADAP NILAI EKSPOR KOPI INDONESIA DALAM 10 TAHUN TERAKHIR (2013-2022)</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Abdur Rafi </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 10, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poltekapp.jpg" class="img-fluid figure-img"></p>
<figcaption>Politeknik APP Jakarta</figcaption>
</figure>
</div>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> PENDAHULUAN</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar Belakang</h3>
<p>Dalam beberapa tahun terakhir, permintaan untuk produk ekspor di seluruh dunia, terutama kopi, telah mengalami peningkatan signifikan. Meskipun kopi menjadi salah satu produk ekspor paling dicari dan menguntungkan, Indonesia menghadapi tantangan dalam mempertahankan pangsa ekspornya ke dunia. Data menunjukkan penurunan pangsa ekspor kopi Indonesia dari 5,1% pada 2005 menjadi 3,8% pada 2015, dengan pergeseran tujuan ekspor ke negara-negara ASEAN dan pasar regional lainnya.</p>
<p>Penyebab utama penurunan ini melibatkan perubahan dalam aturan keamanan pangan di Amerika Serikat, Uni Eropa, dan Jepang, bersamaan dengan penerapan konsep ekonomi hijau dan prinsip keberlanjutan SDGs. Sebagai contoh, di Jerman, peraturan terkait SDGs berdampak pada penurunan impor kopi sejak tahun 2009. Hal ini mendorong Indonesia untuk mengalihkan fokus ekspornya ke pasar ASEAN, seperti Malaysia dan Thailand, serta negara-negara seperti Italia, Rusia, dan Mesir.</p>
<p>Pentingnya peran kewirausahaan petani kopi sebagai UMKM dalam pertumbuhan ekonomi diakui, sejalan dengan teori Kirzner, Hausmann, dan Rodrik. Wirausahawan di sektor kopi Indonesia harus beradaptasi dengan perubahan pasar dan menciptakan peluang baru. Fenomena jaringan produksi atau rantai nilai (GVC) menjadi dasar dalam memahami fragmentasi produksi lintas batas pasar dan negara.</p>
<p>Meskipun kopi tetap menjadi produk ekspor yang menguntungkan, terdapat beberapa masalah terkait dengan ekspor ke dunia. Masalah utama adalah ketergantungan nilai ekspor pada kuantitas produk, dan produsen kopi di seluruh dunia bersaing meningkatkan produksi. Namun, belum jelas bagaimana kuantitas produk berpengaruh terhadap nilai ekspor ke dunia, sehingga analisis lebih lanjut diperlukan.</p>
<p>Penelitian ini bertujuan untuk menganalisis dampak kuantitas produk terhadap nilai ekspor kopi ke negara lain. Data historis dan survei akan digunakan, dan analisis regresi akan dilakukan untuk mengidentifikasi hubungan antara variabel-variabel yang memengaruhi nilai ekspor. Faktor ekonomi seperti harga, inflasi, dan permintaan juga akan dianalisis. Hasil penelitian ini diharapkan memberikan wawasan bagi produsen kopi untuk meningkatkan kuantitas produk mereka dan membantu dalam pengambilan keputusan untuk meningkatkan nilai ekspor kopi ke negara lain.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang Lingkup</h3>
<p>Berdasarkan permasalahan yang telah diidentifikasi, penelitian ini akan difokuskan pada pengaruh kuantitas terhadap nilai ekspor kopi Indonesia.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan Masalah</h3>
<p>Berdasarkan konteks dan masalah yang telah diuraikan sebelumnya, pertanyaan penelitian ini dapat dirumuskan sebagai berikut: 1. Bagaimana kuantitas produk memengaruhi nilai ekspor kopi indonesia?</p>
</section>
<section id="tujuan-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-penelitian"><span class="header-section-number">1.4</span> Tujuan Penelitian</h3>
<p>Dengan merumuskan masalah tersebut, tujuan dari penelitian ini adalah untuk mengidentifikasi sejauh mana dampak kuantitas produk terhadap nilai ekspor kopi Indonesia Manfaat penelitian</p>
</section>
<section id="manfaat-penelitian" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="manfaat-penelitian"><span class="header-section-number">1.5</span> Manfaat Penelitian</h3>
<p>Dalam penulisan penelitian ini, diharapkan bahwa hasil karya ini akan memberikan manfaat baik secara akademis maupun praktis. Berikut adalah manfaat penelitian ini:</p>
<ol type="a">
<li><p><strong>Manfaat Akademis:</strong> Hasil penelitian ini diharapkan dapat menjadi sumber referensi yang berharga bagi penelitian masa depan, khususnya yang terfokus pada dampak kuantitas terhadap nilai ekspor kopi Indonesia</p></li>
<li><p><strong>Manfaat Praktis:</strong></p>
<ul>
<li><strong>Bagi Peneliti:</strong> Penelitian ini diharapkan dapat meningkatkan pemahaman dan wawasan peneliti dalam domain bisnis internasional, terutama dalam konteks ekspor dan impor.</li>
<li><strong>Bagi Masyarakat:</strong> Penelitian ini diharapkan dapat memberikan informasi yang relevan mengenai pengaruh kuantitas terhadap nilai ekspor kopi Indonesia serta dapat menjadi acuan dalam mengembangkan strategi ekspor dan impor yang efektif.</li>
</ul></li>
</ol>
</section>
<section id="package" class="level3" data-number="1.6">
<h3 data-number="1.6" class="anchored" data-anchor-id="package"><span class="header-section-number">1.6</span> Package</h3>
<p>Packages yang digunakan dalam laporan ini antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WDI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> STUDI PUSTAKA</h2>
<section id="daya-saing" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="daya-saing"><span class="header-section-number">2.1</span> Daya Saing</h3>
<p>Daya saing merujuk pada kemampuan suatu wilayah dibandingkan dengan wilayah lain dalam merumuskan strategi yang efektif untuk meningkatkan kesejahteraan masyarakatnya. Secara sederhana, daya saing melibatkan interaksi kompleks antara faktor input (sebagai faktor utama yang membentuk daya saing) dan output (inti dari kinerja ekonomi, yaitu peningkatan kesejahteraan masyarakat) di dalam wilayah tertentu. Analisis daya saing dapat diukur menggunakan konsep Revealed Comparative Advantage (RCA) dan Export Product Dynamics (EPD).</p>
<ol type="1">
<li><p><strong>Teori Revealed Comparative Advantage (RCA)</strong> RCA digunakan sebagai alat analisis untuk mengevaluasi keunggulan komparatif suatu komoditas dalam konteks suatu negara (Kemendag, 2008). Nilai RCA memberikan informasi mengenai tingkat daya saing suatu produk, di mana nilai yang semakin tinggi mengindikasikan daya saing yang lebih tinggi, dan sebaliknya.</p></li>
<li><p><strong>Teori Export Product Dynamics (EPD)</strong> Untuk memahami posisi pangsa pasar, digunakan alat analisis Export Product Dynamics (EPD) dengan berfokus pada dua indikator utama, yaitu peningkatan pangsa pasar ekspor negara dan peningkatan pangsa pasar produk. Analisis EPD, seperti yang diuraikan oleh Tarman et al.&nbsp;(2011), mengidentifikasi empat posisi pangsa pasar berbeda, termasuk Rising Star (peningkatan pangsa pasar ekspor dan produk), Lost Opportunity (penurunan pangsa pasar ekspor, tapi peningkatan pangsa pasar produk), Falling Star (peningkatan pangsa pasar ekspor, tapi penurunan pangsa pasar produk), dan Retreat (penurunan pangsa pasar ekspor dan produk).</p></li>
</ol>
</section>
<section id="faktor-faktor-yang-mempengaruhi-ekspor" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="faktor-faktor-yang-mempengaruhi-ekspor"><span class="header-section-number">2.2</span> Faktor-Faktor yang Mempengaruhi Ekspor</h3>
<p>Ekspor merujuk pada semua barang dan jasa yang dijual ke negara lain, termasuk jasa seperti transportasi, permodalan, dan dukungan lainnya yang mendukung proses ekspor. Terjadinya ekspor dipicu oleh kelebihan penawaran domestik, di mana harga domestik relatif lebih rendah dibandingkan dengan harga di negara lain. Permintaan terhadap volume ekspor kopi dipengaruhi oleh faktor-faktor seperti gross domestic product (GDP), nilai tukar riil, dan harga ekspor kopi. GDP digunakan sebagai indikator pendapatan rata-rata penduduk suatu negara, yang mencerminkan tingkat konsumsi dan daya beli terhadap barang dan jasa tertentu. Nilai tukar riil mengukur harga mata uang suatu negara terhadap mata uang asing, sedangkan harga ekspor kopi dan harga kopi dunia juga memainkan peran penting dalam menentukan permintaan ekspor.</p>
</section>
<section id="kerangka-penelitian" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="kerangka-penelitian"><span class="header-section-number">2.3</span> Kerangka Penelitian</h3>
<p>Komoditas kopi memiliki peran strategis sebagai penyumbang devisa negara dalam subsektor perkebunan, serta sebagai sumber pendapatan bagi petani kopi. Meskipun demikian, produktivitas kopi di Indonesia masih rendah jika dibandingkan dengan negara-negara produsen besar seperti Brazil, Vietnam, dan Kolombia. Penelitian ini akan melakukan analisis daya saing menggunakan metode Revealed Comparative Advantage (RCA) dan Export Product Dynamic (EPD). Selain itu, faktor-faktor yang mempengaruhi volume ekspor kopi Indonesia akan dieksplorasi dengan mempertimbangkan variabel GDP, nilai tukar riil, harga ekspor, dan harga kopi dunia. Hipotesis penelitian melibatkan asumsi bahwa nilai RCA kopi Indonesia diperkirakan lebih dari satu (RCA &gt; 1), menunjukkan keunggulan komparatif yang kuat di pasar internasional. Selain itu, diasumsikan bahwa GDP, nilai tukar riil, harga ekspor, dan harga kopi dunia berpengaruh positif terhadap volume ekspor kopi Indonesia.</p>
</section>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>Data yang digunakan dalam penelitian ini adalah data sekunder selama periode Tahun 2013 – 2022 yang mencakup volume dan nilai ekspor kopi Indonesia, nilai ekspor total dari Indonesia, nilai ekspor kopi dunia, nilai ekspor total dunia, nilai tukar rupiah terhadap dolar AS, dan pertumbuhan ekonomi Indonesia. Data bersumber dari Badan Pusat Statistik dan trade map. Untuk menganalisis pengaruh kuantitas terhadap nilai ekspor kopi Indonesia digunakan formula sebagai berikut: Laursen dalam Imelda (2017). RCA = 𝐗𝒊 𝒊𝒏𝒅𝒐𝒏𝒆𝒔𝒊𝒂 ∑ 𝚾𝒊 𝑰𝒏𝒅𝒐𝒏𝒆𝒔𝒊𝒂 / 𝐗𝒊 𝒘𝒐𝒓𝒍𝒅 ∑ 𝚾𝒊 𝒘𝒐𝒓𝒍𝒅 Dimana: RCA : Revealed Comparative Advantage untuk komoditi i X𝑖 𝑖𝑛𝑑𝑜𝑛𝑒𝑠𝑖𝑎 : Nilai Ekspor komoditas dari Indonesia ∑ Χ𝑖 𝐼𝑛𝑑𝑜𝑛𝑒𝑠𝑖𝑎 : Nilai ekspor total dari Indonesia X𝑖 𝑤𝑜𝑟𝑙𝑑 : Nilai ekspor produk dunia ∑ Χ𝑖 𝑤𝑜𝑟𝑙𝑑 : Nilai ekspor total dunia</p>
<p>Apabila nilai RCA yang didapat lebih besar dari satu maka dapat dikatakan Indonesia memiliki keunggulan komparatif dalam komoditi yang terkait dan mempunyai dayasaing yang kuat. Apabila nilai RCA kurang dari satu maka Indonesia tidak memiliki keunggulan komparatif terhadap komoditi tersebut atau komoditi tersebut dayasaingnya lemah. Semakin tinggi nilai RCA-nya, semakin kuat dayasaingnya (Balassa dalam Ratnawati, 2011). Untuk menganalisis pengaruh produksi kopi, pertumbuhan ekonomi dan kurs terhadap volume ekspor kopi Indonesia di pasar internasional menggunakan metode analisis regresi linier berganda dengan pendekatan model Ordinary Least Square (OLS) atau metode kuadrat terkecil biasa, dengan persamaan sebagai berikut: 𝑳𝒐𝒈𝑽𝒌 = 𝜷𝟎 + 𝜷𝟏𝑳𝒐𝒈𝑷𝑲 + 𝜷𝟐𝑳𝒐𝒈𝑲𝑼𝑹𝑺 + 𝜷𝟑𝑳𝒐𝒈𝑷𝑫𝑩 + 𝒆𝒊 Dimana : 𝐿𝑜𝑔𝑉𝑘 :Volume ekspor kopi 𝐿𝑜𝑔𝛽0 : Konstanta 𝐿𝑜𝑔𝑃𝐾 : Produksi Kopi Indonesia 𝐿𝑜𝑔𝐾𝑈𝑅𝑆 : Nilai tukar rupiah terhadap dollar AS 𝐿𝑜𝑔𝑃𝐷𝐵 : Pertumbuhan ekonomi Indonesia 𝛽1𝛽2 𝛽3 : Koefisien regresi variabel 𝑃𝐾, 𝑃𝐸,𝐾𝑈𝑅𝑆 𝑒𝑖 : Error term</p>
</section>
<section id="data-1" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="data-1"><span class="header-section-number">3.2</span> Data</h3>
<table class="table">
<thead>
<tr class="header">
<th>Tahun</th>
<th>Kuantitas (Tons)</th>
<th>Nilai Ekspor (Ribu USD)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2013</td>
<td>534.025</td>
<td>1.174.044</td>
</tr>
<tr class="even">
<td>2014</td>
<td>384.828</td>
<td>1.039.609</td>
</tr>
<tr class="odd">
<td>2015</td>
<td>502.021</td>
<td>1.197.733</td>
</tr>
<tr class="even">
<td>2016</td>
<td>414.651</td>
<td>1.008.549</td>
</tr>
<tr class="odd">
<td>2017</td>
<td>467.799</td>
<td>1.187.157</td>
</tr>
<tr class="even">
<td>2018</td>
<td>279.961</td>
<td>817.789</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>359.053</td>
<td>883.123</td>
</tr>
<tr class="even">
<td>2020</td>
<td>379.354</td>
<td>821.937</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>387.264</td>
<td>858.558</td>
</tr>
<tr class="even">
<td>2022</td>
<td>437.982</td>
<td>1.149.168</td>
</tr>
</tbody>
</table>
<p>Sumber : ITC Trade Map</p>
<p>Penelitian ini menggunakan data hubungan antara variabel independen dan variabel lainnya, antara kuantitas ekspor dengan nilai ekspor kopi</p>
</section>
<section id="metode-analisis" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.3</span> Metode analisis</h3>
<p>Metode analisis yang digunana yaitu regresi. regresi disebut juga dengan Ordinary Least Square (OLS). Digunakan untuk mencari parameter yang menghubungkan dua variabel. analisis univariat adalah analisis data secara serentak dimana data yang diamati hanya memiliki satu variabel dependen (variabel tidak bebas) pada setiap objek yang diamati.</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah hwy dan <span class="math inline">\(x_t\)</span> adalah cty.</p>
<p>Keterangan : Y disebut juga variabel dependen X disebut juga variabel independent nilai Y dan X kita dapatkan dari data β0 dan β1 disebut parameter. Nilainya kita dapat dari hasil estimasi komputer. μ disebut juga error term / residual. Dia bersifat independen</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> PEMBAHASAN</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Berikut adalah hasil dari plot x dan y, dengan x sebagai kuantitas ekpor kopi Indonesia dan y sebagai nilai (value) ekpor kopi Indonesia. maka didapatkan plot sebagai berikut :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'latihan3.xlsx'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat, <span class="fu">aes</span>(<span class="at">x=</span>X, <span class="at">y=</span>Y))<span class="sc">+</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">'blue'</span>, <span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Tabel 1. Plot Terhadap Nilai Ekspor kopi Indonesia"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"Kuantitas"</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"Nilai Ekspor"</span>,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Sumber: ITC Trade Map"</span>) <span class="sc">+</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil pengaruh jumlah ekspor dan jumlah impor terhadap pertumbuhan ekonomi diestimasi menggunakan regresi multivariat.Hasilnya ditunjukkan sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"latihan3.xlsx"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X,<span class="at">data=</span>dat)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X, data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-126340  -52530    8499   69659   92245 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) 2.453e+05  1.576e+05   1.556  0.15821   
X           1.853e+00  3.747e-01   4.946  0.00113 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 83250 on 8 degrees of freedom
Multiple R-squared:  0.7536,    Adjusted R-squared:  0.7228 
F-statistic: 24.47 on 1 and 8 DF,  p-value: 0.001126</code></pre>
</div>
</div>
<p>Penelitian ini bertujuan untuk menilai efek dari dua variabel, yakni nilai dan kuantitas kopi, terhadap variabel dependen nilai ekspor kopi Indonesia. Hasil analisis regresi menunjukkan bahwa nilai F mencapai 24.47 dengan probabilitas nilai sebesar 0.001126, menunjukkan bahwa keduanya memiliki dampak yang signifikan terhadap ekspor kopi Indonesia selama periode 2013-2022. Koefisien determinasi (R) sebesar 72.28% mengungkapkan sejauh mana variabel independen berkontribusi terhadap variabel dependen, sementara 27,72% sisanya dipengaruhi oleh faktor lain yang tidak dimasukkan dalam penelitian.</p>
<p>Selanjutnya, uji parsial dilakukan untuk mengevaluasi signifikansi individu dari variabel-variabel independen terhadap variabel dependen. Hasil analisis menunjukkan bahwa harga kopi tidak memiliki pengaruh yang signifikan secara parsial terhadap nilai ekspor kopi Indonesia, dengan nilai t-hitung sebesar 1.556 dan probabilitas 0.158 (&gt; 0.1). Di sisi lain, kuantitas kopi secara parsial berpengaruh secara signifikan dengan nilai t-hitung sebesar 4.946 dan probabilitas 0.011 (&lt; 0.1). Dengan demikian, dapat disimpulkan bahwa, pada rentang waktu 2013-2022, kuantitas kopi memiliki dampak yang signifikan terhadap nilai ekspor kopi Indonesia, sementara harga kopi tidak memiliki dampak yang signifikan.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Dapat disimpulkan penelitian ini menunjukkan bahwa kuantitas ekspor kopi memiliki dampak signifikan terhadap nilai ekspor ke dunia. Untuk meningkatkan nilai ekspor, diperlukan langkah-langkah seperti peningkatan kuantitas ekspor melalui promosi produk kopi Indonesia di pasar luar. Selain itu, perbaikan kualitas produk kopi, penurunan biaya ekspor, dan peningkatan kesadaran masyarakat tentang nilai ekspor kopi Indonesia juga diperlukan.</p>
<p>Pemerintah perlu memainkan peran dengan mengurangi beban biaya ekspor, meningkatkan kerja sama dengan pelaku bisnis, dan menciptakan kebijakan yang mendukung ekspor kopi. Peningkatan infrastruktur pengiriman dan kerjasama dengan negara lain juga harus ditingkatkan untuk memastikan distribusi yang efisien. Dengan strategi ini, diharapkan nilai ekspor kopi Indonesia ke dunia dapat meningkat secara signifikan.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Darmawan, A., Wibowo, L. A., &amp; Surachman, A. (n.d.). Coopetition : Jurnal Ilmiah Manajemen Penerapan Rantai Nilai Global Sebagai Strategi Peningkatan Ekspor Produk Kopi.</p>
<p>Daya, A., Made Astuti Wahyu Utami, N., Putra, D. D., &amp; Komala Dewi, R. (2018). ANALISIS DAYA SAING DAN FAKTOR-FAKTOR YANG MEMPENGARUHI EKSPOR KOPI INDONESIA DI PASAR INTERNASIONAL Competitiveness Analysis and Factors Affecting Coffee Exports in the International Market. Jurnal Manajemen Agribisnis, 6(1).</p>
<p>ITC Trade Map. (2022). Retrieved January 11, 2024, from https://www.trademap.org/</p>
<p>Kopi, E., &amp; Bali, P. (2020). Pengaruh Kurs Dollar Amerika Serikat, Inflasi, dan Harga. Jurnal Agribisnis Dan Agrowisata, 9(1). https://ojs.unud.ac.id/index.php/JAA</p>
<p>Muttoharoh, V., Rahma, ;, Candra, N. ;, Prodi, M., Pembangunan, E., Ekonomi, F., &amp; Bisnis, D. (n.d.). Daya saing dan faktor-faktor yang mempengaruhi ekspor kopi Arabika Indonesia di pasar internasional (Vol. 7, Issue 3).</p>
<p>Studi Agribisnis, P., &amp; Pertanian, F. (2018). E-Jurnal Agribisnis dan Agrowisata Analisis Nilai Ekspor Kopi Provinsi Bali dan Faktor-faktor yang Mempengaruhinya SAUMIA KRISNA DEVI DASI, I MADE SUDARMA, IDA AYU LISTIA DEWI. 7(2). https://ojs.unud.ac.id/index.php/JAA256</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>